# Generated by Django 5.2.5 on 2025-10-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('ALI_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ALI_DESCRIPCION', models.CharField(max_length=100)),
                ('ALI_TIPO', models.IntegerField()),
                ('ALI_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('APL_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('APL_DESCRIPCION', models.CharField(max_length=50)),
                ('APL_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('ARC_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ARC_FECHA_HORA', models.DateTimeField(auto_now_add=True)),
                ('ARC_DESCRIPCION', models.CharField(max_length=100)),
                ('ARC_RUTA', models.CharField()),
                ('ARC_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('CAR_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CAR_DESCRIPCION', models.CharField(max_length=100)),
                ('CAR_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('COM_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('COM_DESCRIPCION', models.CharField(max_length=100)),
                ('COM_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concepto_Contable',
            fields=[
                ('COC_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('COC_DESCRIPCION', models.CharField(max_length=100)),
                ('COC_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('DIS_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('DIS_DESCRIPCION', models.CharField(max_length=100)),
                ('DIS_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('ESC_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ESC_DESCRIPCION', models.CharField(max_length=50)),
                ('ESC_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('NIV_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('NIV_DESCRIPCION', models.CharField(max_length=100)),
                ('NIV_ORDEN', models.IntegerField()),
                ('NIV_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('PEL_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PEL_DESCRIPCION', models.CharField(max_length=50)),
                ('PEL_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('PRV_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PRV_DESCRIPCION', models.CharField(max_length=100)),
                ('PRV_CELULAR1', models.CharField(blank=True, max_length=15, null=True)),
                ('PRV_CELULAR2', models.CharField(blank=True, max_length=15, null=True)),
                ('PRV_DIRECCION', models.CharField(blank=True, max_length=100, null=True)),
                ('PRV_OBSERVACION', models.CharField(blank=True, null=True)),
                ('PRV_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('PRO_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PRO_DESCRIPCION', models.CharField(max_length=100)),
                ('PRO_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('RAM_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('RAM_DESCRIPCION', models.CharField(max_length=50)),
                ('RAM_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('REG_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('REG_DESCRIPCION', models.CharField(max_length=100)),
                ('REG_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('ROL_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ROL_DESCRIPCION', models.CharField(max_length=100)),
                ('ROL_TIPO', models.IntegerField()),
                ('ROL_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Archivo',
            fields=[
                ('TAR_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('TAR_DESCRIPCION', models.CharField(max_length=50)),
                ('TAR_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Curso',
            fields=[
                ('TCU_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('TCU_DESCRIPCION', models.CharField(max_length=100)),
                ('TCU_TIPO', models.IntegerField()),
                ('TCU_CANT_PARTICIPANTE', models.IntegerField()),
                ('TCU_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('ZON_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ZON_DESCRIPCION', models.CharField(max_length=100)),
                ('ZON_UNILATERAL', models.BooleanField(default=False)),
                ('ZON_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('CURS_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUR_FECHA_HORA', models.DateTimeField(auto_now_add=True)),
                ('CUR_FECHA_SOLICITUD', models.DateField()),
                ('CUR_CODIGO', models.CharField(max_length=20, unique=True)),
                ('CUR_DESCRIPCION', models.CharField(max_length=255)),
                ('CUR_OBSERVACION', models.CharField(blank=True, max_length=255, null=True)),
                ('CUR_COTA_CON_ALMUERZO', models.IntegerField()),
                ('CUR_COTA_SIN_ALMUERZO', models.IntegerField()),
                ('CUR_MODALIDAD', models.IntegerField()),
                ('CUR_LUGAR', models.CharField(max_length=100)),
                ('CAR_ID_RESPONSABLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_responsable', to='ApiScouts.cargo')),
                ('COM_ID_LUGAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_lugar', to='ApiScouts.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo_Curso',
            fields=[
                ('ARU_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ARC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.archivo')),
                ('CUS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Alimentacion',
            fields=[
                ('CUA_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUA_FECHA', models.DateField()),
                ('CUA_TIEMPO', models.IntegerField()),
                ('CUA_DESCRIPCION', models.CharField(max_length=100)),
                ('CUA_CANTIDAD_ADICIONAL', models.IntegerField(default=0)),
                ('CUA_VIGENTE', models.BooleanField(default=True)),
                ('ALI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.alimentacion')),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Cuota',
            fields=[
                ('CUU_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUU_TIPO', models.IntegerField()),
                ('CUU_FECHA', models.DateField()),
                ('CUU_VALOR', models.IntegerField()),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Fecha',
            fields=[
                ('CUF_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUF_FECHA_INICIO', models.DateField()),
                ('CUF_FECHA_TERMINO', models.DateField()),
                ('CUF_TIPO', models.IntegerField()),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Seccion',
            fields=[
                ('CUS_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUS_SECCION', models.IntegerField()),
                ('CUS_CANT_PARTICIPANTE', models.IntegerField()),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.curso')),
                ('RAM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('GRU_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('GRU_DESCRIPCION', models.CharField(max_length=100)),
                ('GRU_VIGENTE', models.BooleanField(default=True)),
                ('DIS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_Aplicacion',
            fields=[
                ('PEA_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PEA_INGRESAR', models.BooleanField(default=False)),
                ('PEA_MODIFICAR', models.BooleanField(default=False)),
                ('PEA_ELIMINAR', models.BooleanField(default=False)),
                ('PEA_CONSULTAR', models.BooleanField(default=False)),
                ('APL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.aplicacion')),
                ('PEL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('PER_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PER_FECHA_HORA', models.DateTimeField(auto_now_add=True)),
                ('PER_RUN', models.CharField(max_length=9, unique=True)),
                ('PER_DV', models.CharField(max_length=1)),
                ('PER_APELPTA', models.CharField(max_length=50)),
                ('PER_APELMAT', models.CharField(max_length=50)),
                ('PER_NOMBRES', models.CharField(max_length=50)),
                ('PER_MAIL', models.CharField(max_length=100)),
                ('PER_FECHA_NAC', models.DateField()),
                ('PER_DIRECCION', models.CharField(max_length=255)),
                ('PER_FONO', models.CharField(blank=True, max_length=15, null=True)),
                ('PER_ALERGIA_ENFERMEDAD', models.CharField(blank=True, max_length=255, null=True)),
                ('PER_LIMITACION', models.CharField(blank=True, max_length=255, null=True)),
                ('PER_NOM_EMERGENCIA', models.CharField(blank=True, max_length=50, null=True)),
                ('PER_FONO_EMERGENCIA', models.CharField(blank=True, max_length=15, null=True)),
                ('PER_OTROS', models.CharField(blank=True, max_length=255, null=True)),
                ('PER_NUM_MMA', models.IntegerField(blank=True, null=True)),
                ('PER_PROFESION', models.CharField(blank=True, max_length=100, null=True)),
                ('PER_TIEMPO_NNAJ', models.CharField(blank=True, max_length=100, null=True)),
                ('PER_TIEMPO_ADULTO', models.CharField(blank=True, max_length=100, null=True)),
                ('PER_RELIGION', models.CharField(blank=True, max_length=100, null=True)),
                ('PER_APODO', models.CharField(blank=True, max_length=50, null=True)),
                ('PER_FOTO', models.CharField(blank=True, max_length=255, null=True)),
                ('PER_VIGENTE', models.BooleanField(default=True)),
                ('COM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.comuna')),
                ('ESC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.estado_civil')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Coordinador',
            fields=[
                ('CUC_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUC_CARGO', models.CharField(max_length=100)),
                ('CAR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.cargo')),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.curso')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.persona')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='PER_ID_RESPONSABLE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.persona'),
        ),
        migrations.CreateModel(
            name='Archivo_Persona',
            fields=[
                ('ARP_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ARC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.archivo')),
                ('CUS_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.curso')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Curso',
            fields=[
                ('PEC_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PEC_OBSERVACION', models.CharField(blank=True, null=True)),
                ('PEC_REGISTRO', models.BooleanField(default=False)),
                ('PEC_ACREDITACION', models.BooleanField(default=False)),
                ('ALI_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.alimentacion')),
                ('CUS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.curso_seccion')),
                ('NIV_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.nivel')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.persona')),
                ('ROL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Formador',
            fields=[
                ('PEF_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PEF_HAB_1', models.BooleanField(default=False)),
                ('PEF_HAB_2', models.BooleanField(default=False)),
                ('PEF_VERIF', models.BooleanField(default=False)),
                ('PEF_HISTORIAL', models.CharField(blank=True, null=True)),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Grupo',
            fields=[
                ('PEG_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PEG_VIGENTE', models.BooleanField(default=True)),
                ('GRU_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.grupo')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Vehiculo',
            fields=[
                ('PEV_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PEV_MARCA', models.CharField(max_length=50)),
                ('PEV_MODELO', models.CharField(max_length=50)),
                ('PEV_PATENTE', models.CharField(max_length=10)),
                ('PEC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.persona_curso')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='PRO_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.provincia'),
        ),
        migrations.CreateModel(
            name='Persona_Nivel',
            fields=[
                ('PEN_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('NIV_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.nivel')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.persona')),
                ('RAM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.rama')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='REG_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.region'),
        ),
        migrations.CreateModel(
            name='Curso_Formador',
            fields=[
                ('CUF_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUO_DIRECTOR', models.IntegerField()),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.curso')),
                ('CUS_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.curso_seccion')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.persona')),
                ('ROL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.rol')),
            ],
        ),
        migrations.AddField(
            model_name='archivo',
            name='TAR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.tipo_archivo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='TCU_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.tipo_curso'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('USU_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('USU_USERNAME', models.CharField(max_length=100, unique=True)),
                ('USU_PASSWORD', models.CharField(max_length=50)),
                ('USU_RUTA_FOTO', models.CharField(blank=True, max_length=255, null=True)),
                ('USU_VIGENTE', models.BooleanField(default=True)),
                ('PEL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Estado_Curso',
            fields=[
                ('PEU_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PEU_FECHA_HORA', models.DateTimeField(auto_now_add=True)),
                ('PEU_ESTADO', models.IntegerField()),
                ('PEU_VIGENTE', models.BooleanField(default=True)),
                ('PEC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.persona_curso')),
                ('USU_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='USU_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='USU_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.usuario'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='USU_ID_CREA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_crea', to='ApiScouts.usuario'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='USU_ID_MODIFICA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modifica', to='ApiScouts.usuario'),
        ),
        migrations.CreateModel(
            name='Persona_Individual',
            fields=[
                ('PEI_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PEI_VIGENTE', models.BooleanField(default=True)),
                ('CAR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.cargo')),
                ('DIS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.distrito')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.persona')),
                ('ZON_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.zona')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='ZON_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiScouts.zona'),
        ),
    ]
