# Generated by Django 5.2.6 on 2025-10-07 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiScouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacion',
            name='APL_ID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='PRO_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ApiScouts.provincia'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='PEL_ID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil_aplicacion',
            name='APL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ApiScouts.aplicacion'),
        ),
        migrations.AlterField(
            model_name='perfil_aplicacion',
            name='PEA_ID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil_aplicacion',
            name='PEL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ApiScouts.perfil'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='PRO_ID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='REG_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ApiScouts.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='REG_ID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='PEL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ApiScouts.perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='USU_ID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='USU_RUTA_FOTO',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
