# Generated by Django 5.2.6 on 2025-10-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiScouts', '0002_alter_aplicacion_apl_id_alter_comuna_pro_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_curso',
            name='TCU_TIPO',
        ),
        migrations.AlterField(
            model_name='comuna',
            name='COM_ID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_archivo',
            name='TAR_ID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo_curso',
            name='TCU_ID',
            field=models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
