# Generated by Django 5.2.6 on 2025-10-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiScouts', '0003_remove_tipo_curso_tcu_tipo_alter_comuna_com_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_curso',
            name='TCU_ID',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
