# Generated by Django 5.2.6 on 2025-10-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiScouts', '0004_alter_tipo_curso_tcu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_curso',
            name='TCU_TIPO',
            field=models.CharField(choices=[('1', 'Inicial'), ('2', 'Medio'), ('3', 'Avanzado'), ('4', 'Habilitación'), ('5', 'Verificación'), ('6', 'Institucional')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_curso',
            name='TCU_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
