# Generated by Django 5.2.6 on 2025-10-07 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiScouts', '0005_tipo_curso_tcu_tipo_alter_tipo_curso_tcu_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Rol',
            fields=[
                ('TRO_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TRO_NOMBRE', models.CharField(max_length=50, unique=True)),
                ('TRO_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='ALI_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alimentacion',
            name='ALI_TIPO',
            field=models.IntegerField(choices=[(1, 'Con Almuerzo'), (2, 'Sin Almuerzo')]),
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='APL_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='CAR_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='COM_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='PEL_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfil_aplicacion',
            name='PEA_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='PRO_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='REG_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='ROL_DESCRIPCION',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rol',
            name='ROL_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_archivo',
            name='TAR_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipo_curso',
            name='TCU_TIPO',
            field=models.CharField(choices=[(1, 'Inicial'), (2, 'Medio'), (3, 'Avanzado'), (4, 'Habilitación'), (5, 'Verificación'), (6, 'Institucional')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='USU_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='ROL_TIPO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ApiScouts.tipo_rol'),
        ),
    ]
