# Generated by Django 5.2.6 on 2025-10-15 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ModuloMantenedores', '0001_initial'),
        ('ModuloUsuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Curso',
            fields=[
                ('TCU_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TCU_DESCRIPCION', models.CharField(max_length=100)),
                ('TCU_TIPO', models.CharField(choices=[(1, 'Inicial'), (2, 'Medio'), (3, 'Avanzado'), (4, 'Habilitación'), (5, 'Verificación'), (6, 'Institucional')])),
                ('TCU_CANT_PARTICIPANTE', models.IntegerField()),
                ('TCU_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('CURS_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUR_FECHA_HORA', models.DateTimeField(auto_now_add=True)),
                ('CUR_FECHA_SOLICITUD', models.DateField()),
                ('CUR_CODIGO', models.CharField(max_length=20, unique=True)),
                ('CUR_DESCRIPCION', models.CharField(max_length=255)),
                ('CUR_OBSERVACION', models.CharField(blank=True, max_length=255, null=True)),
                ('CUR_COTA_CON_ALMUERZO', models.IntegerField()),
                ('CUR_COTA_SIN_ALMUERZO', models.IntegerField()),
                ('CUR_MODALIDAD', models.IntegerField()),
                ('CUR_LUGAR', models.CharField(max_length=100)),
                ('CAR_ID_RESPONSABLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_responsable', to='ModuloMantenedores.cargo')),
                ('COM_ID_LUGAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_lugar', to='ModuloMantenedores.comuna')),
                ('PER_ID_RESPONSABLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.persona')),
                ('USU_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.usuario')),
                ('TCU_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloCursos.tipo_curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Alimentacion',
            fields=[
                ('CUA_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUA_FECHA', models.DateField()),
                ('CUA_TIEMPO', models.IntegerField()),
                ('CUA_DESCRIPCION', models.CharField(max_length=100)),
                ('CUA_CANTIDAD_ADICIONAL', models.IntegerField(default=0)),
                ('CUA_VIGENTE', models.BooleanField(default=True)),
                ('ALI_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloMantenedores.alimentacion')),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloCursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Coordinador',
            fields=[
                ('CUC_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUC_CARGO', models.CharField(max_length=100)),
                ('CAR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloMantenedores.cargo')),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloCursos.curso')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Cuota',
            fields=[
                ('CUU_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUU_TIPO', models.IntegerField()),
                ('CUU_FECHA', models.DateField()),
                ('CUU_VALOR', models.IntegerField()),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloCursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Fecha',
            fields=[
                ('CUF_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUF_FECHA_INICIO', models.DateField()),
                ('CUF_FECHA_TERMINO', models.DateField()),
                ('CUF_TIPO', models.IntegerField()),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloCursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Seccion',
            fields=[
                ('CUS_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUS_SECCION', models.IntegerField()),
                ('CUS_CANT_PARTICIPANTE', models.IntegerField()),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloCursos.curso')),
                ('RAM_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloMantenedores.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Formador',
            fields=[
                ('CUF_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('CUO_DIRECTOR', models.IntegerField()),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloCursos.curso')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.persona')),
                ('ROL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloMantenedores.rol')),
                ('CUS_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloCursos.curso_seccion')),
            ],
        ),
    ]
