# Generated by Django 5.2.6 on 2025-10-18 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloCursos', '0001_initial'),
        ('ModuloMantenedores', '0002_alter_distrito_dis_id_alter_distrito_zon_id_and_more'),
        ('ModuloUsuarios', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso_alimentacion',
            name='ALI_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.alimentacion'),
        ),
        migrations.AlterField(
            model_name='curso_alimentacion',
            name='CUA_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso_alimentacion',
            name='CUA_TIEMPO',
            field=models.IntegerField(choices=[(1, 'Desayuno'), (2, 'Almuerzo'), (3, 'Once'), (4, 'Cena'), (5, 'Once/Cena')]),
        ),
        migrations.AlterField(
            model_name='curso_alimentacion',
            name='CUR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloCursos.curso'),
        ),
        migrations.AlterField(
            model_name='curso_coordinador',
            name='CAR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.cargo'),
        ),
        migrations.AlterField(
            model_name='curso_coordinador',
            name='CUC_CARGO',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curso_coordinador',
            name='CUC_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso_coordinador',
            name='CUR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloCursos.curso'),
        ),
        migrations.AlterField(
            model_name='curso_coordinador',
            name='PER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarios.persona'),
        ),
        migrations.AlterField(
            model_name='curso_cuota',
            name='CUR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloCursos.curso'),
        ),
        migrations.AlterField(
            model_name='curso_cuota',
            name='CUU_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso_cuota',
            name='CUU_TIPO',
            field=models.IntegerField(choices=[(1, 'Con Almuerzo'), (2, 'Sin Almuerzo')]),
        ),
        migrations.AlterField(
            model_name='curso_cuota',
            name='CUU_VALOR',
            field=models.DecimalField(decimal_places=6, max_digits=21),
        ),
        migrations.AlterField(
            model_name='curso_fecha',
            name='CUF_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso_fecha',
            name='CUF_TIPO',
            field=models.IntegerField(choices=[(1, 'Presencial'), (2, 'Online'), (3, 'Hibrido')]),
        ),
        migrations.AlterField(
            model_name='curso_fecha',
            name='CUR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloCursos.curso'),
        ),
        migrations.AlterField(
            model_name='curso_formador',
            name='CUF_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso_formador',
            name='CUO_DIRECTOR',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curso_formador',
            name='CUR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloCursos.curso'),
        ),
        migrations.AlterField(
            model_name='curso_formador',
            name='CUS_ID',
            field=models.ForeignKey(default='nullo', on_delete=django.db.models.deletion.PROTECT, to='ModuloCursos.curso_seccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso_formador',
            name='PER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarios.persona'),
        ),
        migrations.AlterField(
            model_name='curso_formador',
            name='ROL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.rol'),
        ),
        migrations.AlterField(
            model_name='curso_seccion',
            name='CUR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloCursos.curso'),
        ),
        migrations.AlterField(
            model_name='curso_seccion',
            name='CUS_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso_seccion',
            name='RAM_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.rama'),
        ),
        migrations.AlterField(
            model_name='tipo_curso',
            name='TCU_CANT_PARTICIPANTE',
            field=models.IntegerField(null=True),
        ),
    ]
