# Generated by Django 5.2.8 on 2025-12-12 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('ali_id', models.BigAutoField(db_column='ali_id', primary_key=True, serialize=False)),
                ('ali_descripcion', models.CharField(db_column='ali_descripcion', max_length=100)),
                ('ali_tipo', models.IntegerField(choices=[(1, 'Con Almuerzo'), (2, 'Sin Almuerzo')], db_column='ali_tipo')),
                ('ali_vigente', models.BooleanField(db_column='ali_vigente', default=True)),
            ],
            options={
                'db_table': 'alimentacion',
            },
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('apl_id', models.BigAutoField(db_column='apl_id', primary_key=True, serialize=False)),
                ('apl_descripcion', models.CharField(db_column='apl_descripcion', max_length=50)),
                ('apl_vigente', models.BooleanField(db_column='apl_vigente', default=True)),
            ],
            options={
                'db_table': 'aplicacion',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('arc_id', models.BigAutoField(db_column='arc_id', primary_key=True, serialize=False)),
                ('arc_fecha_hora', models.DateTimeField(auto_now_add=True, db_column='arc_fecha_hora')),
                ('arc_descripcion', models.CharField(db_column='arc_descripcion', max_length=100)),
                ('arc_ruta', models.CharField(db_column='arc_ruta', max_length=255)),
                ('arc_vigente', models.BooleanField(db_column='arc_vigente', default=True)),
            ],
            options={
                'db_table': 'archivo',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('car_id', models.BigAutoField(db_column='car_id', primary_key=True, serialize=False)),
                ('car_descripcion', models.CharField(db_column='car_descripcion', max_length=100)),
                ('car_vigente', models.BooleanField(db_column='car_vigente', default=True)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('com_id', models.BigAutoField(db_column='com_id', primary_key=True, serialize=False)),
                ('com_descripcion', models.CharField(db_column='com_descripcion', max_length=100)),
                ('com_vigente', models.BooleanField(db_column='com_vigente', default=True)),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Concepto_Contable',
            fields=[
                ('coc_id', models.BigAutoField(db_column='coc_id', primary_key=True, serialize=False)),
                ('coc_descripcion', models.CharField(db_column='coc_descripcion', max_length=50)),
                ('coc_vigente', models.BooleanField(db_column='coc_vigente', default=True)),
            ],
            options={
                'db_table': 'concepto_contable',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('dis_id', models.BigAutoField(db_column='dis_id', primary_key=True, serialize=False)),
                ('dis_descripcion', models.CharField(db_column='dis_descripcion', max_length=100)),
                ('dis_vigente', models.BooleanField(db_column='dis_vigente', default=True)),
            ],
            options={
                'db_table': 'distrito',
            },
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('esc_id', models.BigAutoField(db_column='esc_id', primary_key=True, serialize=False)),
                ('esc_descripcion', models.CharField(db_column='esc_descripcion', max_length=50)),
                ('esc_vigente', models.BooleanField(db_column='esc_vigente', default=True)),
            ],
            options={
                'db_table': 'estado_civil',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('niv_id', models.BigAutoField(db_column='niv_id', primary_key=True, serialize=False)),
                ('niv_descripcion', models.CharField(db_column='niv_descripcion', max_length=50)),
                ('niv_orden', models.IntegerField(db_column='niv_orden')),
                ('niv_vigente', models.BooleanField(db_column='niv_vigente', default=True)),
            ],
            options={
                'db_table': 'nivel',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('pel_id', models.BigAutoField(db_column='pel_id', primary_key=True, serialize=False)),
                ('pel_descripcion', models.CharField(db_column='pel_descripcion', max_length=50)),
                ('pel_vigente', models.BooleanField(db_column='pel_vigente', default=True)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('prv_id', models.BigAutoField(db_column='prv_id', primary_key=True, serialize=False)),
                ('prv_descripcion', models.CharField(db_column='prv_descripcion', max_length=100)),
                ('prv_celular1', models.CharField(blank=True, db_column='prv_celular1', max_length=15)),
                ('prv_celular2', models.CharField(blank=True, db_column='prv_celular2', max_length=15, null=True)),
                ('prv_direccion', models.CharField(blank=True, db_column='prv_direccion', max_length=100)),
                ('prv_observacion', models.CharField(blank=True, db_column='prv_observacion', max_length=500, null=True)),
                ('prv_vigente', models.BooleanField(db_column='prv_vigente', default=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('pro_id', models.BigAutoField(db_column='pro_id', primary_key=True, serialize=False)),
                ('pro_descripcion', models.CharField(db_column='pro_descripcion', max_length=100)),
                ('pro_vigente', models.BooleanField(db_column='pro_vigente', default=True)),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('ram_id', models.BigAutoField(db_column='ram_id', primary_key=True, serialize=False)),
                ('ram_descripcion', models.CharField(db_column='ram_descripcion', max_length=50)),
                ('ram_vigente', models.BooleanField(db_column='ram_vigente', default=True)),
            ],
            options={
                'db_table': 'rama',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('reg_id', models.BigAutoField(db_column='reg_id', primary_key=True, serialize=False)),
                ('reg_descripcion', models.CharField(db_column='reg_descripcion', max_length=100)),
                ('reg_vigente', models.BooleanField(db_column='reg_vigente', default=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.BigAutoField(db_column='rol_id', primary_key=True, serialize=False)),
                ('rol_descripcion', models.CharField(db_column='rol_descripcion', max_length=50)),
                ('rol_tipo', models.IntegerField(choices=[(1, 'Participante'), (2, 'Formadores'), (3, 'Apoyo Formadores'), (4, 'Organización'), (5, 'Servicio'), (6, 'Salud')], db_column='rol_tipo')),
                ('rol_vigente', models.BooleanField(db_column='rol_vigente', default=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Archivo',
            fields=[
                ('tar_id', models.BigAutoField(db_column='tar_id', primary_key=True, serialize=False)),
                ('tar_descripcion', models.CharField(db_column='tar_descripcion', max_length=50)),
                ('tar_vigente', models.BooleanField(db_column='tar_vigente', default=True)),
            ],
            options={
                'db_table': 'tipo_archivo',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Curso',
            fields=[
                ('tcu_id', models.BigAutoField(db_column='tcu_id', primary_key=True, serialize=False)),
                ('tcu_descripcion', models.CharField(db_column='tcu_descripcion', max_length=100)),
                ('tcu_tipo', models.IntegerField(choices=[(1, 'Inicial'), (2, 'Medio'), (3, 'Avanzado'), (4, 'Habilitación'), (5, 'Verificación'), (6, 'Institucional')], db_column='tcu_tipo')),
                ('tcu_cant_participante', models.IntegerField(db_column='tcu_cant_participante', null=True)),
                ('tcu_vigente', models.BooleanField(db_column='tcu_vigente', default=True)),
            ],
            options={
                'db_table': 'tipo_curso',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('zon_id', models.BigAutoField(db_column='zon_id', primary_key=True, serialize=False)),
                ('zon_descripcion', models.CharField(db_column='zon_descripcion', max_length=100)),
                ('zon_unilateral', models.BooleanField(db_column='zon_unilateral', default=False)),
                ('zon_vigente', models.BooleanField(db_column='zon_vigente', default=True)),
            ],
            options={
                'db_table': 'zona',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cur_id', models.BigAutoField(db_column='cur_id', primary_key=True, serialize=False)),
                ('cur_fecha_hora', models.DateTimeField(auto_now_add=True, db_column='cur_fecha_hora')),
                ('cur_fecha_solicitud', models.DateTimeField(db_column='cur_fecha_solicitud')),
                ('cur_codigo', models.CharField(db_column='cur_codigo', max_length=20, unique=True)),
                ('cur_descripcion', models.CharField(db_column='cur_descripcion', max_length=255)),
                ('cur_observacion', models.CharField(blank=True, db_column='cur_observacion', max_length=255, null=True)),
                ('cur_administra', models.IntegerField(choices=[(1, 'Zona'), (2, 'Distrito')], db_column='cur_administra')),
                ('cur_cota_con_almuerzo', models.IntegerField(db_column='cur_cuota_con_almuerzo', default=0)),
                ('cur_cota_sin_almuerzo', models.IntegerField(db_column='cur_cuota_sin_almuerzo', default=0)),
                ('cur_modalidad', models.IntegerField(choices=[(1, 'Internado'), (2, 'Externado'), (3, 'Internado/Externado')], db_column='cur_modalidad')),
                ('cur_tipo_curso', models.IntegerField(choices=[(1, 'Presencial'), (2, 'Online'), (3, 'Hibrido')], db_column='cur_tipo_curso')),
                ('cur_lugar', models.CharField(db_column='cur_lugar', max_length=100)),
                ('cur_coord_latitud', models.CharField(db_column='cur_coord_latitud', max_length=50, null=True)),
                ('cur_coord_longitud', models.CharField(db_column='cur_coord_longitud', max_length=50, null=True)),
                ('cur_estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Vigente'), (2, 'Anulado'), (3, 'Finalizado')], db_column='cur_estado')),
                ('car_id_responsable', models.ForeignKey(db_column='car_id_responsable', on_delete=django.db.models.deletion.CASCADE, related_name='cargo_responsable', to='ApiCoreScouts.cargo')),
                ('com_id_lugar', models.ForeignKey(db_column='com_id_lugar', on_delete=django.db.models.deletion.CASCADE, related_name='comuna_lugar', to='ApiCoreScouts.comuna')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Comprobante_Pago',
            fields=[
                ('cpa_id', models.BigAutoField(db_column='cpa_id', primary_key=True, serialize=False)),
                ('cpa_fecha_hora', models.DateTimeField(db_column='cpa_fecha_hora')),
                ('cpa_fecha', models.DateField(auto_now_add=True, db_column='cpa_fecha')),
                ('cpa_numero', models.IntegerField(db_column='cpa_numero')),
                ('cpa_valor', models.DecimalField(db_column='cpa_valor', decimal_places=2, max_digits=21)),
                ('coc_id', models.ForeignKey(db_column='coc_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.concepto_contable')),
                ('pec_id', models.ForeignKey(db_column='pec_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
            ],
            options={
                'db_table': 'comprobante_pago',
            },
        ),
        migrations.CreateModel(
            name='Curso_Alimentacion',
            fields=[
                ('cua_id', models.BigAutoField(db_column='cua_id', primary_key=True, serialize=False)),
                ('cua_fecha', models.DateTimeField(db_column='cua_fecha')),
                ('cua_tiempo', models.IntegerField(choices=[(1, 'Desayuno'), (2, 'Almuerzo'), (3, 'Once'), (4, 'Cena'), (5, 'Once/Cena')], db_column='cua_tiempo')),
                ('cua_descripcion', models.CharField(db_column='cua_descripcion', max_length=100)),
                ('cua_cantidad_adicional', models.IntegerField(db_column='cua_cantidad_adicional', default=0)),
                ('cua_vigente', models.BooleanField(db_column='cua_vigente', default=True)),
                ('ali_id', models.ForeignKey(db_column='ali_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.alimentacion')),
                ('cur_id', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
            ],
            options={
                'db_table': 'curso_alimentacion',
            },
        ),
        migrations.CreateModel(
            name='Curso_Cuota',
            fields=[
                ('cuu_id', models.BigAutoField(db_column='cuu_id', primary_key=True, serialize=False)),
                ('cuu_tipo', models.IntegerField(choices=[(1, 'Con Almuerzo'), (2, 'Sin Almuerzo')], db_column='cuu_tipo')),
                ('cuu_fecha', models.DateTimeField(db_column='cuu_fecha')),
                ('cuu_valor', models.DecimalField(db_column='cuu_valor', decimal_places=6, max_digits=21)),
                ('cur_id', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
            ],
            options={
                'db_table': 'curso_cuota',
            },
        ),
        migrations.CreateModel(
            name='Curso_Fecha',
            fields=[
                ('cuf_id', models.BigAutoField(db_column='cuf_id', primary_key=True, serialize=False)),
                ('cuf_fecha_inicio', models.DateTimeField(db_column='cuf_fecha_inicio')),
                ('cuf_fecha_termino', models.DateTimeField(db_column='cuf_fecha_termino')),
                ('cuf_tipo', models.IntegerField(choices=[(1, 'Presencial'), (2, 'Online'), (3, 'Hibrido')], db_column='cuf_tipo')),
                ('cur_id', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
            ],
            options={
                'db_table': 'curso_fecha',
            },
        ),
        migrations.CreateModel(
            name='Curso_Seccion',
            fields=[
                ('cus_id', models.BigAutoField(db_column='cus_id', primary_key=True, serialize=False)),
                ('cus_seccion', models.IntegerField(db_column='cus_seccion')),
                ('cus_cant_participante', models.IntegerField(db_column='cus_cant_participante')),
                ('cur_id', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
                ('ram_id', models.ForeignKey(db_column='ram_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.rama')),
            ],
            options={
                'db_table': 'curso_seccion',
            },
        ),
        migrations.CreateModel(
            name='Archivo_Curso',
            fields=[
                ('aru_id', models.BigAutoField(db_column='aru_id', primary_key=True, serialize=False)),
                ('arc_id', models.ForeignKey(db_column='arc_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.archivo')),
                ('cus_id', models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso_seccion')),
            ],
            options={
                'db_table': 'archivo_curso',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('gru_id', models.BigAutoField(db_column='gru_id', primary_key=True, serialize=False)),
                ('gru_descripcion', models.CharField(db_column='gru_descripcion', max_length=100)),
                ('gru_vigente', models.BooleanField(db_column='gru_vigente', default=True)),
                ('dis_id', models.ForeignKey(db_column='dis_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.distrito')),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Pago_Persona',
            fields=[
                ('pap_id', models.BigAutoField(db_column='pap_id', primary_key=True, serialize=False)),
                ('pap_fecha_hora', models.DateTimeField(db_column='pap_fecha_hora')),
                ('pap_tipo', models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Egreso')], db_column='pap_tipo', null=True)),
                ('pap_valor', models.DecimalField(db_column='pap_valor', decimal_places=6, max_digits=21)),
                ('pap_estado', models.IntegerField(choices=[(1, 'Pagado'), (2, 'Anulado')], db_column='pap_estado')),
                ('pap_observacion', models.CharField(db_column='pap_observacion', max_length=500, null=True)),
                ('cur_id', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
            ],
            options={
                'db_table': 'pago_persona',
            },
        ),
        migrations.CreateModel(
            name='Pago_Comprobante',
            fields=[
                ('pco_id', models.BigAutoField(db_column='pco_id', primary_key=True, serialize=False)),
                ('cpa_id', models.ForeignKey(db_column='cpa_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.comprobante_pago')),
                ('pap_id', models.ForeignKey(db_column='pap_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.pago_persona')),
            ],
            options={
                'db_table': 'pago_comprobante',
            },
        ),
        migrations.CreateModel(
            name='Perfil_Aplicacion',
            fields=[
                ('pea_id', models.BigAutoField(db_column='pea_id', primary_key=True, serialize=False)),
                ('pea_ingresar', models.BooleanField(db_column='pea_ingresar', default=False)),
                ('pea_modificar', models.BooleanField(db_column='pea_modificar', default=False)),
                ('pea_eliminar', models.BooleanField(db_column='pea_eliminar', default=False)),
                ('pea_consultar', models.BooleanField(db_column='pea_consultar', default=False)),
                ('apl_id', models.ForeignKey(db_column='apl_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.aplicacion')),
                ('pel_id', models.ForeignKey(db_column='pel_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.perfil')),
            ],
            options={
                'db_table': 'perfil_aplicacion',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('per_id', models.BigAutoField(db_column='per_id', primary_key=True, serialize=False)),
                ('per_fecha_hora', models.DateTimeField(auto_now_add=True, db_column='per_fecha_hora')),
                ('per_run', models.CharField(db_column='per_run', max_length=9, unique=True)),
                ('per_dv', models.CharField(db_column='per_dv', max_length=1)),
                ('per_apelpta', models.CharField(db_column='per_apelpat', max_length=50)),
                ('per_apelmat', models.CharField(db_column='per_apelmat', max_length=50, null=True)),
                ('per_nombres', models.CharField(db_column='per_nombres', max_length=50)),
                ('per_mail', models.CharField(db_column='per_email', max_length=100)),
                ('per_fecha_nac', models.DateTimeField(db_column='per_fecha_nac')),
                ('per_direccion', models.CharField(db_column='per_direccion', max_length=255)),
                ('per_tipo_fono', models.IntegerField(choices=[(1, 'Fono Fijo'), (2, 'Celular'), (3, 'Celular/WhatsApp'), (4, 'WhatsApp')], db_column='per_tipo_fono')),
                ('per_fono', models.CharField(blank=True, db_column='per_fono', max_length=15)),
                ('per_alergia_enfermedad', models.CharField(db_column='per_alergia_enfermedad', max_length=255, null=True)),
                ('per_limitacion', models.CharField(db_column='per_limitacion', max_length=255, null=True)),
                ('per_nom_emergencia', models.CharField(db_column='per_nom_emergencia', max_length=50, null=True)),
                ('per_fono_emergencia', models.CharField(db_column='per_fono_emergencia', max_length=15, null=True)),
                ('per_otros', models.CharField(db_column='per_otros', max_length=255, null=True)),
                ('per_num_mma', models.IntegerField(db_column='per_num_mmaa', null=True)),
                ('per_profesion', models.CharField(db_column='per_profesion', max_length=100, null=True)),
                ('per_tiempo_nnaj', models.CharField(db_column='per_tiempo_nnaj', max_length=100, null=True)),
                ('per_tiempo_adulto', models.CharField(db_column='per_tiempo_adulto', max_length=100, null=True)),
                ('per_religion', models.CharField(db_column='per_religion', max_length=100, null=True)),
                ('per_apodo', models.CharField(db_column='per_apodo', max_length=50)),
                ('per_foto', models.CharField(db_column='per_foto', max_length=255, null=True)),
                ('per_vigente', models.BooleanField(db_column='per_vigente', default=True)),
                ('com_id', models.ForeignKey(db_column='com_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.comuna')),
                ('esc_id', models.ForeignKey(db_column='esc_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.estado_civil')),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.AddField(
            model_name='pago_persona',
            name='per_id',
            field=models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona'),
        ),
        migrations.CreateModel(
            name='Curso_Coordinador',
            fields=[
                ('cuc_id', models.BigAutoField(db_column='cuc_id', primary_key=True, serialize=False)),
                ('cuc_cargo', models.CharField(db_column='cuc_cargo', max_length=100, null=True)),
                ('car_id', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.cargo')),
                ('cur_id', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
            ],
            options={
                'db_table': 'curso_coordinador',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='per_id_responsable',
            field=models.ForeignKey(db_column='per_id_responsable', on_delete=django.db.models.deletion.CASCADE, to='ApiCoreScouts.persona'),
        ),
        migrations.CreateModel(
            name='Archivo_Persona',
            fields=[
                ('arp_id', models.BigAutoField(db_column='arp_id', primary_key=True, serialize=False)),
                ('arc_id', models.ForeignKey(db_column='arc_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.archivo')),
                ('cus_id', models.ForeignKey(db_column='cus_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiCoreScouts.curso_seccion')),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
            ],
            options={
                'db_table': 'archivo_persona',
            },
        ),
        migrations.CreateModel(
            name='Persona_Curso',
            fields=[
                ('pec_id', models.BigAutoField(db_column='pec_id', primary_key=True, serialize=False)),
                ('pec_observacion', models.CharField(blank=True, db_column='pec_observacion', max_length=500, null=True)),
                ('pec_registro', models.BooleanField(db_column='pec_registro', default=False)),
                ('pec_acreditacion', models.BooleanField(db_column='pec_acreditado', default=False)),
                ('pec_envio_correo_qr', models.BooleanField(db_column='pec_envio_correo_qr', default=False)),
                ('ali_id', models.ForeignKey(blank=True, db_column='ali_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.alimentacion')),
                ('cus_id', models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso_seccion')),
                ('niv_id', models.ForeignKey(db_column='niv_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.nivel')),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
                ('rol_id', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.rol')),
            ],
            options={
                'db_table': 'persona_curso',
            },
        ),
        migrations.CreateModel(
            name='Persona_Formador',
            fields=[
                ('pef_id', models.BigAutoField(db_column='pef_id', primary_key=True, serialize=False)),
                ('pef_hab_1', models.BooleanField(db_column='pef_hab_1', default=False)),
                ('pef_hab_2', models.BooleanField(db_column='pef_hab_2', default=False)),
                ('pef_verif', models.BooleanField(db_column='pef_verif', default=False)),
                ('pef_historial', models.CharField(blank=True, db_column='pef_historial', max_length=500, null=True)),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
            ],
            options={
                'db_table': 'persona_formador',
            },
        ),
        migrations.CreateModel(
            name='Persona_Grupo',
            fields=[
                ('peg_id', models.BigAutoField(db_column='peg_id', primary_key=True, serialize=False)),
                ('peg_vigente', models.BooleanField(db_column='peg_vigente', default=True)),
                ('gru_id', models.ForeignKey(db_column='gru_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.grupo')),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
            ],
            options={
                'db_table': 'persona_grupo',
            },
        ),
        migrations.CreateModel(
            name='Persona_Vehiculo',
            fields=[
                ('pev_id', models.BigAutoField(db_column='pev_id', primary_key=True, serialize=False)),
                ('pev_marca', models.CharField(db_column='pev_marca', max_length=50)),
                ('pev_modelo', models.CharField(db_column='pev_modelo', max_length=50)),
                ('pev_patente', models.CharField(db_column='pev_patente', max_length=10)),
                ('pec_id', models.ForeignKey(db_column='pec_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona_curso')),
            ],
            options={
                'db_table': 'persona_vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Prepago',
            fields=[
                ('ppa_id', models.BigAutoField(db_column='ppa_id', primary_key=True, serialize=False)),
                ('ppa_valor', models.DecimalField(db_column='ppa_valor', decimal_places=6, max_digits=21)),
                ('ppa_observacion', models.CharField(db_column='ppa_observacion', max_length=500, null=True)),
                ('ppa_vigente', models.BooleanField(db_column='ppa_vigente', default=True)),
                ('cur_id', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
                ('pap_id', models.ForeignKey(db_column='pap_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.pago_persona')),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
            ],
            options={
                'db_table': 'prepago',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='pro_id',
            field=models.ForeignKey(db_column='pro_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.provincia'),
        ),
        migrations.CreateModel(
            name='Persona_Nivel',
            fields=[
                ('pen_id', models.BigAutoField(db_column='pen_id', primary_key=True, serialize=False)),
                ('niv_id', models.ForeignKey(db_column='niv_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.nivel')),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
                ('ram_id', models.ForeignKey(db_column='ram_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.rama')),
            ],
            options={
                'db_table': 'persona_nivel',
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='reg_id',
            field=models.ForeignKey(db_column='reg_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.region'),
        ),
        migrations.CreateModel(
            name='Curso_Formador',
            fields=[
                ('cuf_id', models.BigAutoField(db_column='cuf_id', primary_key=True, serialize=False)),
                ('cuo_director', models.BooleanField(db_column='cuo_director', default=False)),
                ('cur_id', models.ForeignKey(db_column='cur_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
                ('cus_id', models.ForeignKey(db_column='cus_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso_seccion')),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
                ('rol_id', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.rol')),
            ],
            options={
                'db_table': 'curso_formador',
            },
        ),
        migrations.AddField(
            model_name='archivo',
            name='tar_id',
            field=models.ForeignKey(db_column='tar_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.tipo_archivo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tcu_id',
            field=models.ForeignKey(db_column='tcu_id', on_delete=django.db.models.deletion.CASCADE, to='ApiCoreScouts.tipo_curso'),
        ),
        migrations.CreateModel(
            name='Persona_Individual',
            fields=[
                ('pei_id', models.BigAutoField(db_column='pei_id', primary_key=True, serialize=False)),
                ('pei_vigente', models.BooleanField(db_column='pei_vigente', default=True)),
                ('car_id', models.ForeignKey(db_column='car_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.cargo')),
                ('dis_id', models.ForeignKey(db_column='dis_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.distrito')),
                ('per_id', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
                ('zon_id', models.ForeignKey(db_column='zon_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.zona')),
            ],
            options={
                'db_table': 'persona_individual',
            },
        ),
        migrations.AddField(
            model_name='distrito',
            name='zon_id',
            field=models.ForeignKey(db_column='zon_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.zona'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.BigAutoField(db_column='usu_id', primary_key=True, serialize=False)),
                ('usu_username', models.CharField(db_column='usu_username', max_length=100, unique=True)),
                ('usu_email', models.EmailField(db_column='usu_email', max_length=255, null=True)),
                ('password', models.CharField(db_column='usu_password', max_length=128)),
                ('usu_ruta_foto', models.CharField(db_column='usu_ruta_foto', max_length=255, null=True)),
                ('usu_vigente', models.BooleanField(db_column='usu_vigente', default=True)),
                ('is_staff', models.BooleanField(db_column='usu_is_staff', default=False)),
                ('is_superuser', models.BooleanField(db_column='usu_is_superuser', default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('pel_id', models.ForeignKey(db_column='pel_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.perfil')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Persona_Estado_Curso',
            fields=[
                ('peu_id', models.BigAutoField(db_column='peu_id', primary_key=True, serialize=False)),
                ('peu_fecha_hora', models.DateTimeField(auto_now_add=True, db_column='peu_fecha_hora')),
                ('peu_estado', models.IntegerField(choices=[(1, 'Pre Inscrito'), (2, 'Avisado'), (3, 'Lista de Espera'), (4, 'Inscrito'), (5, 'Vigente'), (6, 'Anulado'), (7, 'Sobrecupo')], db_column='peu_estado')),
                ('peu_vigente', models.BooleanField(db_column='peu_vigente', default=True)),
                ('pec_id', models.ForeignKey(db_column='pec_id', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona_curso')),
                ('usu_id', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'persona_estado_curso',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='usu_id',
            field=models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago_persona',
            name='usu_id',
            field=models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='usu_id',
            field=models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobante_pago',
            name='usu_id',
            field=models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='usu_id_crea',
            field=models.ForeignKey(db_column='usu_id_crea', on_delete=django.db.models.deletion.PROTECT, related_name='usuario_crea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='usu_id_modifica',
            field=models.ForeignKey(db_column='usu_id_modifica', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modifica', to=settings.AUTH_USER_MODEL),
        ),
    ]
