# Generated by Django 5.2.6 on 2025-11-02 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('ALI_ID', models.BigAutoField(db_column='ALI_ID', primary_key=True, serialize=False)),
                ('ALI_DESCRIPCION', models.CharField(db_column='ALI_DESCRIPCION', max_length=100)),
                ('ALI_TIPO', models.IntegerField(choices=[(1, 'Con Almuerzo'), (2, 'Sin Almuerzo')], db_column='ALI_TIPO')),
                ('ALI_VIGENTE', models.BooleanField(db_column='ALI_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'ALIMENTACION',
            },
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('APL_ID', models.BigAutoField(db_column='APL_ID', primary_key=True, serialize=False)),
                ('APL_DESCRIPCION', models.CharField(db_column='APL_DESCRIPCION', max_length=50)),
                ('APL_VIGENTE', models.BooleanField(db_column='APL_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'APLICACION',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('ARC_ID', models.BigAutoField(db_column='ARC_ID', primary_key=True, serialize=False)),
                ('ARC_FECHA_HORA', models.DateTimeField(auto_now_add=True, db_column='ARC_FECHA_HORA')),
                ('ARC_DESCRIPCION', models.CharField(db_column='ARC_DESCRIPCION', max_length=100)),
                ('ARC_RUTA', models.CharField(db_column='ARC_RUTA', max_length=255)),
                ('ARC_VIGENTE', models.BooleanField(db_column='ARC_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'ARCHIVO',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('CAR_ID', models.BigAutoField(db_column='CAR_ID', primary_key=True, serialize=False)),
                ('CAR_DESCRIPCION', models.CharField(db_column='CAR_DESCRIPCION', max_length=100)),
                ('CAR_VIGENTE', models.BooleanField(db_column='CAR_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'CARGO',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('COM_ID', models.BigAutoField(db_column='COM_ID', primary_key=True, serialize=False)),
                ('COM_DESCRIPCION', models.CharField(db_column='COM_DESCRIPCION', max_length=100)),
                ('COM_VIGENTE', models.BooleanField(db_column='COM_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'COMUNA',
            },
        ),
        migrations.CreateModel(
            name='Concepto_Contable',
            fields=[
                ('COC_ID', models.BigAutoField(db_column='COC_ID', primary_key=True, serialize=False)),
                ('COC_DESCRIPCION', models.CharField(db_column='COC_DESCRIPCION', max_length=50)),
                ('COC_VIGENTE', models.BooleanField(db_column='COC_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'CONCEPTO_CONTABLE',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('DIS_ID', models.BigAutoField(db_column='DIS_ID', primary_key=True, serialize=False)),
                ('DIS_DESCRIPCION', models.CharField(db_column='DIS_DESCRIPCION', max_length=100)),
                ('DIS_VIGENTE', models.BooleanField(db_column='DIS_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'DISTRITO',
            },
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('ESC_ID', models.BigAutoField(db_column='ESC_ID', primary_key=True, serialize=False)),
                ('ESC_DESCRIPCION', models.CharField(db_column='ESC_DESCRIPCION', max_length=50)),
                ('ESC_VIGENTE', models.BooleanField(db_column='ESC_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'ESTADO_CIVIL',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('NIV_ID', models.BigAutoField(db_column='NIV_ID', primary_key=True, serialize=False)),
                ('NIV_DESCRIPCION', models.CharField(db_column='NIV_DESCRIPCION', max_length=50)),
                ('NIV_ORDEN', models.IntegerField(db_column='NIV_ORDEN')),
                ('NIV_VIGENTE', models.BooleanField(db_column='NIV_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'NIVEL',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('PEL_ID', models.BigAutoField(db_column='PEL_ID', primary_key=True, serialize=False)),
                ('PEL_DESCRIPCION', models.CharField(db_column='PEL_DESCRIPCION', max_length=50)),
                ('PEL_VIGENTE', models.BooleanField(db_column='PEL_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'PERFIL',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('PRV_ID', models.BigAutoField(db_column='PRV_ID', primary_key=True, serialize=False)),
                ('PRV_DESCRIPCION', models.CharField(db_column='PRV_DESCRIPCION', max_length=100)),
                ('PRV_CELULAR1', models.CharField(blank=True, db_column='PRV_CELULAR1', max_length=15)),
                ('PRV_CELULAR2', models.CharField(blank=True, db_column='PRV_CELULAR2', max_length=15, null=True)),
                ('PRV_DIRECCION', models.CharField(blank=True, db_column='PRV_DIRECCION', max_length=100)),
                ('PRV_OBSERVACION', models.CharField(blank=True, db_column='PRV_OBSERVACION', max_length=500, null=True)),
                ('PRV_VIGENTE', models.BooleanField(db_column='PRV_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'PROVEEDOR',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('PRO_ID', models.BigAutoField(db_column='PRO_ID', primary_key=True, serialize=False)),
                ('PRO_DESCRIPCION', models.CharField(db_column='PRO_DESCRIPCION', max_length=100)),
                ('PRO_VIGENTE', models.BooleanField(db_column='PRO_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'PROVINCIA',
            },
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('RAM_ID', models.BigAutoField(db_column='RAM_ID', primary_key=True, serialize=False)),
                ('RAM_DESCRIPCION', models.CharField(db_column='RAM_DESCRIPCION', max_length=50)),
                ('RAM_VIGENTE', models.BooleanField(db_column='RAM_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'RAMA',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('REG_ID', models.BigAutoField(db_column='REG_ID', primary_key=True, serialize=False)),
                ('REG_DESCRIPCION', models.CharField(db_column='REG_DESCRIPCION', max_length=100)),
                ('REG_VIGENTE', models.BooleanField(db_column='REG_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'REGION',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('ROL_ID', models.BigAutoField(db_column='ROL_ID', primary_key=True, serialize=False)),
                ('ROL_DESCRIPCION', models.CharField(db_column='ROL_DESCRIPCION', max_length=50)),
                ('ROL_TIPO', models.IntegerField(choices=[(1, 'Participante'), (2, 'Formadores'), (3, 'Apoyo Formadores'), (4, 'Organización'), (5, 'Servicio'), (6, 'Salud')], db_column='ROL_TIPO')),
                ('ROL_VIGENTE', models.BooleanField(db_column='ROL_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'ROL',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Archivo',
            fields=[
                ('TAR_ID', models.BigAutoField(db_column='TAR_ID', primary_key=True, serialize=False)),
                ('TAR_DESCRIPCION', models.CharField(db_column='TAR_DESCRIPCION', max_length=50)),
                ('TAR_VIGENTE', models.BooleanField(db_column='TAR_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'TIPO_ARCHIVO',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Curso',
            fields=[
                ('TCU_ID', models.BigAutoField(db_column='TCU_ID', primary_key=True, serialize=False)),
                ('TCU_DESCRIPCION', models.CharField(db_column='TCU_DESCRIPCION', max_length=100)),
                ('TCU_TIPO', models.IntegerField(choices=[(1, 'Inicial'), (2, 'Medio'), (3, 'Avanzado'), (4, 'Habilitación'), (5, 'Verificación'), (6, 'Institucional')], db_column='TCU_TIPO')),
                ('TCU_CANT_PARTICIPANTE', models.IntegerField(db_column='TCU_CANT_PARTICIPANTE', null=True)),
                ('TCU_VIGENTE', models.BooleanField(db_column='TCU_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'TIPO_CURSO',
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('ZON_ID', models.BigAutoField(db_column='ZON_ID', primary_key=True, serialize=False)),
                ('ZON_DESCRIPCION', models.CharField(db_column='ZON_DESCRIPCION', max_length=100)),
                ('ZON_UNILATERAL', models.BooleanField(db_column='ZON_UNILATERAL', default=False)),
                ('ZON_VIGENTE', models.BooleanField(db_column='ZON_VIGENTE', default=True)),
            ],
            options={
                'db_table': 'ZONA',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('CUR_ID', models.BigAutoField(db_column='CUR_ID', primary_key=True, serialize=False)),
                ('CUR_FECHA_HORA', models.DateTimeField(auto_now_add=True, db_column='CUR_FECHA_HORA')),
                ('CUR_FECHA_SOLICITUD', models.DateField(db_column='CUR_FECHA_SOLICITUD')),
                ('CUR_CODIGO', models.CharField(db_column='CUR_CODIGO', max_length=20, unique=True)),
                ('CUR_DESCRIPCION', models.CharField(db_column='CUR_DESCRIPCION', max_length=255)),
                ('CUR_OBSERVACION', models.CharField(blank=True, db_column='CUR_OBSERVACION', max_length=255, null=True)),
                ('CUR_ADMINISTRA', models.IntegerField(choices=[(2, 'Zona'), (2, 'Distrito')], db_column='CUR_ADMINISTRA')),
                ('CUR_COTA_CON_ALMUERZO', models.IntegerField(db_column='CUR_COTA_CON_ALMUERZO')),
                ('CUR_COTA_SIN_ALMUERZO', models.IntegerField(db_column='CUR_COTA_SIN_ALMUERZO')),
                ('CUR_MODALIDAD', models.IntegerField(choices=[(1, 'Internado'), (2, 'Externado'), (3, 'Internado/Externado')], db_column='CUR_MODALIDAD')),
                ('CUR_TIPO_CURSO', models.IntegerField(choices=[(1, 'Presencial'), (2, 'Online'), (3, 'Hibrido')], db_column='CUR_TIPO_CURSO')),
                ('CUR_LUGAR', models.CharField(db_column='CUR_LUGAR', max_length=100)),
                ('CUR_COORD_LATITUD', models.CharField(db_column='CUR_COORD_LATITUD', max_length=50, null=True)),
                ('CUR_COORD_LONGITUD', models.CharField(db_column='CUR_COORD_LONGITUD', max_length=50, null=True)),
                ('CUR_ESTADO', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Vigente'), (2, 'Anulado'), (3, 'Finalizado')], db_column='CUR_ESTADO')),
                ('CAR_ID_RESPONSABLE', models.ForeignKey(db_column='CAR_ID_RESPONSABLE', on_delete=django.db.models.deletion.CASCADE, related_name='cargo_responsable', to='ApiCoreScouts.cargo')),
                ('COM_ID_LUGAR', models.ForeignKey(db_column='COM_ID_LUGAR', on_delete=django.db.models.deletion.CASCADE, related_name='comuna_lugar', to='ApiCoreScouts.comuna')),
            ],
            options={
                'db_table': 'CURSO',
            },
        ),
        migrations.CreateModel(
            name='Comprobante_Pago',
            fields=[
                ('CPA_ID', models.BigAutoField(db_column='CPA_ID', primary_key=True, serialize=False)),
                ('CPA_FECHA_HORA', models.DateTimeField(db_column='CPA_FECHA_HORA')),
                ('CPA_FECHA', models.DateField(auto_now_add=True, db_column='CPA_FECHA')),
                ('CPA_NUMERO', models.IntegerField(db_column='CPA_NUMERO')),
                ('CPA_VALOR', models.DecimalField(db_column='CPA_VALOR', decimal_places=2, max_digits=21)),
                ('COC_ID', models.ForeignKey(db_column='COC_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.concepto_contable')),
                ('PEC_ID', models.ForeignKey(db_column='PEC_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
            ],
            options={
                'db_table': 'COMPROBANTE_PAGO',
            },
        ),
        migrations.CreateModel(
            name='Curso_Alimentacion',
            fields=[
                ('CUA_ID', models.BigAutoField(db_column='CUA_ID', primary_key=True, serialize=False)),
                ('CUA_FECHA', models.DateField(db_column='CUA_FECHA')),
                ('CUA_TIEMPO', models.IntegerField(choices=[(1, 'Desayuno'), (2, 'Almuerzo'), (3, 'Once'), (4, 'Cena'), (5, 'Once/Cena')], db_column='CUA_TIEMPO')),
                ('CUA_DESCRIPCION', models.CharField(db_column='CUA_DESCRIPCION', max_length=100)),
                ('CUA_CANTIDAD_ADICIONAL', models.IntegerField(db_column='CUA_CANTIDAD_ADICIONAL', default=0)),
                ('CUA_VIGENTE', models.BooleanField(db_column='CUA_VIGENTE', default=True)),
                ('ALI_ID', models.ForeignKey(db_column='ALI_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.alimentacion')),
                ('CUR_ID', models.ForeignKey(db_column='CUR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
            ],
            options={
                'db_table': 'CURSO_ALIMENTACION',
            },
        ),
        migrations.CreateModel(
            name='Curso_Cuota',
            fields=[
                ('CUU_ID', models.BigAutoField(db_column='CUU_ID', primary_key=True, serialize=False)),
                ('CUU_TIPO', models.IntegerField(choices=[(1, 'Con Almuerzo'), (2, 'Sin Almuerzo')], db_column='CUU_TIPO')),
                ('CUU_FECHA', models.DateField(db_column='CUU_FECHA')),
                ('CUU_VALOR', models.DecimalField(db_column='CUU_VALOR', decimal_places=6, max_digits=21)),
                ('CUR_ID', models.ForeignKey(db_column='CUR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
            ],
            options={
                'db_table': 'CURSO_CUOTA',
            },
        ),
        migrations.CreateModel(
            name='Curso_Fecha',
            fields=[
                ('CUF_ID', models.BigAutoField(db_column='CUF_ID', primary_key=True, serialize=False)),
                ('CUF_FECHA_INICIO', models.DateField(db_column='CUF_FECHA_INICIO')),
                ('CUF_FECHA_TERMINO', models.DateField(db_column='CUF_FECHA_TERMINO')),
                ('CUF_TIPO', models.IntegerField(choices=[(1, 'Presencial'), (2, 'Online'), (3, 'Hibrido')], db_column='CUF_TIPO')),
                ('CUR_ID', models.ForeignKey(db_column='CUR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
            ],
            options={
                'db_table': 'CURSO_FECHA',
            },
        ),
        migrations.CreateModel(
            name='Curso_Seccion',
            fields=[
                ('CUS_ID', models.BigAutoField(db_column='CUS_ID', primary_key=True, serialize=False)),
                ('CUS_SECCION', models.IntegerField(db_column='CUS_SECCION')),
                ('CUS_CANT_PARTICIPANTE', models.IntegerField(db_column='CUS_CANT_PARTICIPANTE')),
                ('CUR_ID', models.ForeignKey(db_column='CUR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
                ('RAM_ID', models.ForeignKey(db_column='RAM_ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.rama')),
            ],
            options={
                'db_table': 'CURSO_SECCION',
            },
        ),
        migrations.CreateModel(
            name='Archivo_Curso',
            fields=[
                ('ARU_ID', models.BigAutoField(db_column='ARU_ID', primary_key=True, serialize=False)),
                ('ARC_ID', models.ForeignKey(db_column='ARC_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.archivo')),
                ('CUS_ID', models.ForeignKey(db_column='CUS_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso_seccion')),
            ],
            options={
                'db_table': 'ARCHIVO_CURSO',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('GRU_ID', models.BigAutoField(db_column='GRU_ID', primary_key=True, serialize=False)),
                ('GRU_DESCRIPCION', models.CharField(db_column='GRU_DESCRIPCION', max_length=100)),
                ('GRU_VIGENTE', models.BooleanField(db_column='GRU_VIGENTE', default=True)),
                ('DIS_ID', models.ForeignKey(db_column='DIS_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.distrito')),
            ],
            options={
                'db_table': 'GRUPO',
            },
        ),
        migrations.CreateModel(
            name='Pago_Persona',
            fields=[
                ('PAP_ID', models.BigAutoField(db_column='PAP_ID', primary_key=True, serialize=False)),
                ('PAP_FECHA_HORA', models.DateTimeField(db_column='PAP_FECHA_HORA')),
                ('PAP_TIPO', models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Egreso')], db_column='PAP_TIPO', null=True)),
                ('PAP_VALOR', models.DecimalField(db_column='PAP_VALOR', decimal_places=6, max_digits=21)),
                ('PAP_ESTADO', models.IntegerField(choices=[(1, 'Pagado'), (2, 'Anulado')], db_column='PAP_ESTADO')),
                ('PAP_OBSERVACION', models.CharField(db_column='PAP_OBSERVACION', max_length=500, null=True)),
                ('CUR_ID', models.ForeignKey(db_column='CUR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
            ],
            options={
                'db_table': 'PAGO_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='Pago_Comprobante',
            fields=[
                ('PCO_ID', models.BigAutoField(db_column='PCO_ID', primary_key=True, serialize=False)),
                ('CPA_ID', models.ForeignKey(db_column='CPA_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.comprobante_pago')),
                ('PAP_ID', models.ForeignKey(db_column='PAP_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.pago_persona')),
            ],
            options={
                'db_table': 'PAGO_COMPROBANTE',
            },
        ),
        migrations.CreateModel(
            name='Perfil_Aplicacion',
            fields=[
                ('PEA_ID', models.BigAutoField(db_column='PEA_ID', primary_key=True, serialize=False)),
                ('PEA_INGRESAR', models.BooleanField(db_column='PEA_INGRESAR', default=False)),
                ('PEA_MODIFICAR', models.BooleanField(db_column='PEA_MODIFICAR', default=False)),
                ('PEA_ELIMINAR', models.BooleanField(db_column='PEA_ELIMINAR', default=False)),
                ('PEA_CONSULTAR', models.BooleanField(db_column='PEA_CONSULTAR', default=False)),
                ('APL_ID', models.ForeignKey(db_column='APL_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.aplicacion')),
                ('PEL_ID', models.ForeignKey(db_column='PEL_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.perfil')),
            ],
            options={
                'db_table': 'PERFIL_APLICACION',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('PER_ID', models.BigAutoField(db_column='PER_ID', primary_key=True, serialize=False)),
                ('PER_FECHA_HORA', models.DateTimeField(auto_now_add=True, db_column='PER_FECHA_HORA')),
                ('PER_RUN', models.CharField(db_column='PER_RUN', max_length=9, unique=True)),
                ('PER_DV', models.CharField(db_column='PER_DV', max_length=1)),
                ('PER_APELPTA', models.CharField(db_column='PER_APELPTA', max_length=50)),
                ('PER_APELMAT', models.CharField(db_column='PER_APELMAT', max_length=50, null=True)),
                ('PER_NOMBRES', models.CharField(db_column='PER_NOMBRES', max_length=50)),
                ('PER_MAIL', models.CharField(db_column='PER_MAIL', max_length=100)),
                ('PER_FECHA_NAC', models.DateField(db_column='PER_FECHA_NAC')),
                ('PER_DIRECCION', models.CharField(db_column='PER_DIRECCION', max_length=255)),
                ('PER_TIPO_FONO', models.IntegerField(choices=[(1, 'Fono Fijo'), (2, 'Celular'), (3, 'Celular/WhatsApp'), (4, 'WhatsApp')], db_column='PER_TIPO_FONO')),
                ('PER_FONO', models.CharField(blank=True, db_column='PER_FONO', max_length=15)),
                ('PER_ALERGIA_ENFERMEDAD', models.CharField(db_column='PER_ALERGIA_ENFERMEDAD', max_length=255, null=True)),
                ('PER_LIMITACION', models.CharField(db_column='PER_LIMITACION', max_length=255, null=True)),
                ('PER_NOM_EMERGENCIA', models.CharField(db_column='PER_NOM_EMERGENCIA', max_length=50, null=True)),
                ('PER_FONO_EMERGENCIA', models.CharField(db_column='PER_FONO_EMERGENCIA', max_length=15, null=True)),
                ('PER_OTROS', models.CharField(db_column='PER_OTROS', max_length=255, null=True)),
                ('PER_NUM_MMA', models.IntegerField(db_column='PER_NUM_MMA', null=True)),
                ('PER_PROFESION', models.CharField(db_column='PER_PROFESION', max_length=100, null=True)),
                ('PER_TIEMPO_NNAJ', models.CharField(db_column='PER_TIEMPO_NNAJ', max_length=100, null=True)),
                ('PER_TIEMPO_ADULTO', models.CharField(db_column='PER_TIEMPO_ADULTO', max_length=100, null=True)),
                ('PER_RELIGION', models.CharField(db_column='PER_RELIGION', max_length=100, null=True)),
                ('PER_APODO', models.CharField(db_column='PER_APODO', max_length=50)),
                ('PER_FOTO', models.CharField(db_column='PER_FOTO', max_length=255, null=True)),
                ('PER_VIGENTE', models.BooleanField(db_column='PER_VIGENTE', default=True)),
                ('COM_ID', models.ForeignKey(db_column='COM_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.comuna')),
                ('ESC_ID', models.ForeignKey(db_column='ESC_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.estado_civil')),
            ],
            options={
                'db_table': 'PERSONA',
            },
        ),
        migrations.AddField(
            model_name='pago_persona',
            name='PER_ID',
            field=models.ForeignKey(db_column='PER_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona'),
        ),
        migrations.CreateModel(
            name='Curso_Coordinador',
            fields=[
                ('CUC_ID', models.BigAutoField(db_column='CUC_ID', primary_key=True, serialize=False)),
                ('CUC_CARGO', models.CharField(db_column='CUC_CARGO', max_length=100, null=True)),
                ('CAR_ID', models.ForeignKey(db_column='CAR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.cargo')),
                ('CUR_ID', models.ForeignKey(db_column='CUR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
                ('PER_ID', models.ForeignKey(db_column='PER_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
            ],
            options={
                'db_table': 'CURSO_COORDINADOR',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='PER_ID_RESPONSABLE',
            field=models.ForeignKey(db_column='PER_ID_RESPONSABLE', on_delete=django.db.models.deletion.CASCADE, to='ApiCoreScouts.persona'),
        ),
        migrations.CreateModel(
            name='Archivo_Persona',
            fields=[
                ('ARP_ID', models.BigAutoField(db_column='ARP_ID', primary_key=True, serialize=False)),
                ('ARC_ID', models.ForeignKey(db_column='ARC_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.archivo')),
                ('CUS_ID', models.ForeignKey(db_column='CUS_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiCoreScouts.curso_seccion')),
                ('PER_ID', models.ForeignKey(db_column='PER_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
            ],
            options={
                'db_table': 'ARCHIVO_PERSONA',
            },
        ),
        migrations.CreateModel(
            name='Persona_Curso',
            fields=[
                ('PEC_ID', models.BigAutoField(db_column='PEC_ID', primary_key=True, serialize=False)),
                ('PEC_OBSERVACION', models.CharField(blank=True, db_column='PEC_OBSERVACION', max_length=500, null=True)),
                ('PEC_REGISTRO', models.BooleanField(db_column='PEC_REGISTRO', default=False)),
                ('PEC_ACREDITACION', models.BooleanField(db_column='PEC_ACREDITACION', default=False)),
                ('PEC_ENVIO_CORREO_QR', models.BooleanField(db_column='PEC_ENVIO_CORREO_QR', default=False)),
                ('ALI_ID', models.ForeignKey(blank=True, db_column='ALI_ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.alimentacion')),
                ('CUS_ID', models.ForeignKey(db_column='CUS_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso_seccion')),
                ('NIV_ID', models.ForeignKey(db_column='NIV_ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.nivel')),
                ('PER_ID', models.ForeignKey(db_column='PER_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
                ('ROL_ID', models.ForeignKey(db_column='ROL_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.rol')),
            ],
            options={
                'db_table': 'PERSONA_CURSO',
            },
        ),
        migrations.CreateModel(
            name='Persona_Formador',
            fields=[
                ('PEF_ID', models.BigAutoField(db_column='PEF_ID', primary_key=True, serialize=False)),
                ('PEF_HAB_1', models.BooleanField(db_column='PEF_HAB_1', default=False)),
                ('PEF_HAB_2', models.BooleanField(db_column='PEF_HAB_2', default=False)),
                ('PEF_VERIF', models.BooleanField(db_column='PEF_VERIF', default=False)),
                ('PEF_HISTORIAL', models.CharField(blank=True, db_column='PEF_HISTORIAL', max_length=500, null=True)),
                ('PER_ID', models.ForeignKey(db_column='PER_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
            ],
            options={
                'db_table': 'PERSONA_FORMADOR',
            },
        ),
        migrations.CreateModel(
            name='Persona_Grupo',
            fields=[
                ('PEG_ID', models.BigAutoField(db_column='PEG_ID', primary_key=True, serialize=False)),
                ('PEG_VIGENTE', models.BooleanField(db_column='PEG_VIGENTE', default=True)),
                ('GRU_ID', models.ForeignKey(db_column='GRU_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.grupo')),
                ('PER_ID', models.ForeignKey(db_column='PER_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
            ],
            options={
                'db_table': 'PERSONA_GRUPO',
            },
        ),
        migrations.CreateModel(
            name='Persona_Vehiculo',
            fields=[
                ('PEV_ID', models.BigAutoField(db_column='PEV_ID', primary_key=True, serialize=False)),
                ('PEV_MARCA', models.CharField(db_column='PEV_MARCA', max_length=50)),
                ('PEV_MODELO', models.CharField(db_column='PEV_MODELO', max_length=50)),
                ('PEV_PATENTE', models.CharField(db_column='PEV_PATENTE', max_length=10)),
                ('PEC_ID', models.ForeignKey(db_column='PEC_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona_curso')),
            ],
            options={
                'db_table': 'PERSONA_VEHICULO',
            },
        ),
        migrations.CreateModel(
            name='Prepago',
            fields=[
                ('PPA_ID', models.BigAutoField(db_column='PPA_ID', primary_key=True, serialize=False)),
                ('PPA_VALOR', models.DecimalField(db_column='PPA_VALOR', decimal_places=6, max_digits=21)),
                ('PPA_OBSERVACION', models.CharField(db_column='PPA_OBSERVACION', max_length=500, null=True)),
                ('PPA_VIGENTE', models.BooleanField(db_column='PPA_VIGENTE', default=True)),
                ('CUR_ID', models.ForeignKey(db_column='CUR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
                ('PAP_ID', models.ForeignKey(db_column='PAP_ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.pago_persona')),
                ('PER_ID', models.ForeignKey(db_column='PER_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
            ],
            options={
                'db_table': 'PREPAGO',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='PRO_ID',
            field=models.ForeignKey(db_column='PRO_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.provincia'),
        ),
        migrations.CreateModel(
            name='Persona_Nivel',
            fields=[
                ('PEN_ID', models.BigAutoField(db_column='PEN_ID', primary_key=True, serialize=False)),
                ('NIV_ID', models.ForeignKey(db_column='NIV_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.nivel')),
                ('PER_ID', models.ForeignKey(db_column='PER_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
                ('RAM_ID', models.ForeignKey(db_column='RAM_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.rama')),
            ],
            options={
                'db_table': 'PERSONA_NIVEL',
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='REG_ID',
            field=models.ForeignKey(db_column='REG_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.region'),
        ),
        migrations.CreateModel(
            name='Curso_Formador',
            fields=[
                ('CUF_ID', models.BigAutoField(db_column='CUF_ID', primary_key=True, serialize=False)),
                ('CUO_DIRECTOR', models.BooleanField(db_column='CUO_DIRECTOR', default=False)),
                ('CUR_ID', models.ForeignKey(db_column='CUR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso')),
                ('CUS_ID', models.ForeignKey(db_column='CUS_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso_seccion')),
                ('PER_ID', models.ForeignKey(db_column='PER_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
                ('ROL_ID', models.ForeignKey(db_column='ROL_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.rol')),
            ],
            options={
                'db_table': 'CURSO_FORMADOR',
            },
        ),
        migrations.AddField(
            model_name='archivo',
            name='TAR_ID',
            field=models.ForeignKey(db_column='TAR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.tipo_archivo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='TCU_ID',
            field=models.ForeignKey(db_column='TCU_ID', on_delete=django.db.models.deletion.CASCADE, to='ApiCoreScouts.tipo_curso'),
        ),
        migrations.CreateModel(
            name='Persona_Individual',
            fields=[
                ('PEI_ID', models.BigAutoField(db_column='PEI_ID', primary_key=True, serialize=False)),
                ('PEI_VIGENTE', models.BooleanField(db_column='PEI_VIGENTE', default=True)),
                ('CAR_ID', models.ForeignKey(db_column='CAR_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.cargo')),
                ('DIS_ID', models.ForeignKey(db_column='DIS_ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.distrito')),
                ('PER_ID', models.ForeignKey(db_column='PER_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona')),
                ('ZON_ID', models.ForeignKey(db_column='ZON_ID', null=True, on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.zona')),
            ],
            options={
                'db_table': 'PERSONA_INDIVIDUAL',
            },
        ),
        migrations.AddField(
            model_name='distrito',
            name='ZON_ID',
            field=models.ForeignKey(db_column='ZON_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.zona'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('USU_ID', models.BigAutoField(db_column='USU_ID', primary_key=True, serialize=False)),
                ('USU_USERNAME', models.CharField(db_column='USU_USERNAME', max_length=100, unique=True)),
                ('USU_PASSWORD', models.CharField(db_column='USU_PASSWORD', max_length=255)),
                ('USU_RUTA_FOTO', models.CharField(db_column='USU_RUTA_FOTO', max_length=255)),
                ('USU_VIGENTE', models.BooleanField(db_column='USU_VIGENTE', default=True)),
                ('PEL_ID', models.ForeignKey(db_column='PEL_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.perfil')),
            ],
            options={
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Persona_Estado_Curso',
            fields=[
                ('PEU_ID', models.BigAutoField(db_column='PEU_ID', primary_key=True, serialize=False)),
                ('PEU_FECHA_HORA', models.DateTimeField(auto_now_add=True, db_column='PEU_FECHA_HORA')),
                ('PEU_ESTADO', models.IntegerField(choices=[(1, 'Pre Inscrito'), (2, 'Avisado'), (3, 'Lista de Espera'), (4, 'Inscrito'), (5, 'Vigente'), (6, 'Anulado'), (7, 'Sobrecupo')], db_column='PEU_ESTADO')),
                ('PEU_VIGENTE', models.BooleanField(db_column='PEU_VIGENTE', default=True)),
                ('PEC_ID', models.ForeignKey(db_column='PEC_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.persona_curso')),
                ('USU_ID', models.ForeignKey(db_column='USU_ID', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PERSONA_ESTADO_CURSO',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='USU_ID',
            field=models.ForeignKey(db_column='USU_ID', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago_persona',
            name='USU_ID',
            field=models.ForeignKey(db_column='USU_ID', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='USU_ID',
            field=models.ForeignKey(db_column='USU_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobante_pago',
            name='USU_ID',
            field=models.ForeignKey(db_column='USU_ID', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='USU_ID_CREA',
            field=models.ForeignKey(db_column='USU_ID_CREA', on_delete=django.db.models.deletion.PROTECT, related_name='usuario_crea', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='USU_ID_MODIFICA',
            field=models.ForeignKey(db_column='USU_ID_MODIFICA', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modifica', to=settings.AUTH_USER_MODEL),
        ),
    ]
