# Generated by Django 5.2.8 on 2026-02-24 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCoreScouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='car_id_responsable',
            field=models.ForeignKey(blank=True, db_column='car_id_responsable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_responsable', to='ApiCoreScouts.cargo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='per_id_responsable',
            field=models.ForeignKey(blank=True, db_column='per_id_responsable', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiCoreScouts.persona'),
        ),
    ]
