# Generated by Django 5.2.6 on 2025-10-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCoreScouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='CUR_ID',
            field=models.BigAutoField(db_column='CUR_ID', primary_key=True, serialize=False),
        ),
    ]
