# Generated by Django 5.2.6 on 2025-11-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCoreScouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='USU_PASSWORD',
            field=models.CharField(db_column='USU_PASSWORD', max_length=128),
        ),
    ]
