# Generated by Django 5.2.6 on 2025-10-26 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCoreScouts', '0002_alter_curso_cur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo_curso',
            name='CUS_ID',
            field=models.ForeignKey(db_column='CUS_ID', on_delete=django.db.models.deletion.PROTECT, to='ApiCoreScouts.curso_seccion'),
        ),
        migrations.AlterField(
            model_name='archivo_persona',
            name='CUS_ID',
            field=models.ForeignKey(db_column='CUS_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='ApiCoreScouts.curso_seccion'),
        ),
    ]
