# Generated by Django 5.2.6 on 2025-10-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCoreScouts', '0003_alter_archivo_curso_cus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='CUR_COORD_LATITUD',
            field=models.CharField(db_column='CUR_COORD_LATITUD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='CUR_COORD_LONGITUD',
            field=models.CharField(db_column='CUR_COORD_LONGITUD', max_length=50, null=True),
        ),
    ]
