# Generated by Django 5.2.8 on 2026-03-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCoreScouts', '0003_remove_perfil_aplicacion_apl_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'permissions': [('view_screen', 'Puede visualizar la pantalla de Cursos')]},
        ),
        migrations.AlterModelOptions(
            name='pago_persona',
            options={'permissions': [('view_screen_pago_persona', 'Puede visualizar la pantalla de Pagos')]},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'permissions': [('view_screen_persona', 'Puede visualizar la pantalla de Personas')]},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'permissions': [('view_screen_rol', 'Puede visualizar la pantalla de Perfiles')]},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('view_screen_usuario', 'Puede visualizar la pantalla de Usuarios')], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
