# Generated by Django 5.2.8 on 2026-03-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCoreScouts', '0004_alter_curso_options_alter_pago_persona_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'permissions': [('view_screen_curso', 'Puede visualizar la pantalla de Cursos')]},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('view_screen_usuario', 'Puede visualizar la pantalla de Usuarios'), ('view_screen_perfil', 'Puede visualizar la pantalla de Perfiles'), ('view_screen_correo', 'Puede visualizar la pantalla de Correos'), ('view_screen_acreditacion_manual', 'Puede visualizar la pantalla de Acreditación Manual'), ('view_screen_verificador_qr', 'Puede visualizar la pantalla de Verificador QR')], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
