# Generated by Django 5.2.8 on 2026-04-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCoreScouts', '0005_add_screen_permissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAmbito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(choices=[(1, 'Grupo (Restricto)'), (2, 'Distrito'), (3, 'Zona'), (4, 'Global')], db_column='pam_nivel', default=4, verbose_name='Nivel de Acceso')),
                ('distrito', models.ForeignKey(blank=True, db_column='pam_dis_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ambitos', to='ApiCoreScouts.distrito', verbose_name='Distrito')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambito', to='auth.group', verbose_name='Perfil')),
                ('grupo', models.ForeignKey(blank=True, db_column='pam_gru_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ambitos', to='ApiCoreScouts.grupo', verbose_name='Grupo')),
                ('zona', models.ForeignKey(blank=True, db_column='pam_zon_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ambitos', to='ApiCoreScouts.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Ámbito de Perfil',
                'verbose_name_plural': 'Ámbitos de Perfil',
                'db_table': 'perfil_ambito',
            },
        ),
    ]
