# Generated by Django 5.2.8 on 2026-04-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiCoreScouts', '0006_add_perfil_ambito'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona_formador',
            name='pef_vigente',
            field=models.BooleanField(db_column='pef_vigente', default=True),
        ),
    ]
