# Generated by Django 5.2.6 on 2025-10-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('ALI_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ALI_DESCRIPCION', models.CharField(max_length=100)),
                ('ALI_TIPO', models.IntegerField(choices=[(1, 'Con Almuerzo'), (2, 'Sin Almuerzo')])),
                ('ALI_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('CAR_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CAR_DESCRIPCION', models.CharField(max_length=100)),
                ('CAR_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('DIS_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('DIS_DESCRIPCION', models.CharField(max_length=100)),
                ('DIS_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('ESC_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ESC_DESCRIPCION', models.CharField(max_length=50)),
                ('ESC_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('NIV_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NIV_DESCRIPCION', models.CharField(max_length=50)),
                ('NIV_ORDEN', models.IntegerField()),
                ('NIV_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('PRO_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PRO_DESCRIPCION', models.CharField(max_length=100)),
                ('PRO_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('RAM_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RAM_DESCRIPCION', models.CharField(max_length=50)),
                ('RAM_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('REG_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('REG_DESCRIPCION', models.CharField(max_length=100)),
                ('REG_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('ROL_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ROL_DESCRIPCION', models.CharField(max_length=50)),
                ('ROL_TIPO', models.IntegerField(choices=[(1, 'Participante'), (2, 'Formadores'), (3, 'Apoyo Formadores'), (4, 'Organización'), (5, 'Servicio'), (6, 'Salud')])),
                ('ROL_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('ZON_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ZON_DESCRIPCION', models.CharField(max_length=100)),
                ('ZON_UNILATERAL', models.BooleanField(default=False)),
                ('ZON_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('GRU_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('GRU_DESCRIPCION', models.CharField(max_length=100)),
                ('GRU_VIGENTE', models.BooleanField(default=True)),
                ('DIS_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('COM_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('COM_DESCRIPCION', models.CharField(max_length=100)),
                ('COM_VIGENTE', models.BooleanField(default=True)),
                ('PRO_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='REG_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.region'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='ZON_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.zona'),
        ),
    ]
