# Generated by Django 5.2.6 on 2025-10-18 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloMantenedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='DIS_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='ZON_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.zona'),
        ),
        migrations.AlterField(
            model_name='estado_civil',
            name='ESC_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='DIS_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.distrito'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='GRU_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='NIV_DESCRIPCION',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='NIV_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rama',
            name='RAM_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rol',
            name='ROL_TIPO',
            field=models.IntegerField(choices=[(1, 'Participante'), (2, 'Formadores'), (3, 'Apoyo Formadores'), (4, 'Organización'), (5, 'Servicio'), (6, 'Salud')]),
        ),
        migrations.AlterField(
            model_name='zona',
            name='ZON_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
