# Generated by Django 5.2.6 on 2025-10-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ModuloUsuarioCurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto_Contable',
            fields=[
                ('COC_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('COC_DESCRIPCION', models.CharField(max_length=50)),
                ('COC_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('PRV_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PRV_DESCRIPCION', models.CharField(max_length=100)),
                ('PRV_CELULAR1', models.CharField(blank=True, max_length=15)),
                ('PRV_CELULAR2', models.CharField(blank=True, max_length=15, null=True)),
                ('PRV_DIRECCION', models.CharField(blank=True, max_length=100)),
                ('PRV_OBSERVACION', models.CharField(blank=True, max_length=500, null=True)),
                ('PRV_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante_Pago',
            fields=[
                ('CPA_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CPA_FECHA_HORA', models.DateTimeField()),
                ('CPA_FECHA', models.DateField(auto_now_add=True)),
                ('CPA_NUMERO', models.IntegerField()),
                ('CPA_VALOR', models.DecimalField(decimal_places=2, max_digits=21)),
                ('PEC_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona_curso')),
                ('USU_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.usuario')),
                ('COC_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloPagos.concepto_contable')),
            ],
        ),
        migrations.CreateModel(
            name='Pago_Persona',
            fields=[
                ('PAP_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PAP_FECHA_HORA', models.DateTimeField()),
                ('PAP_VALOR', models.DecimalField(decimal_places=6, max_digits=21)),
                ('PAP_OBSERVACION', models.CharField(max_length=500, null=True)),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.curso')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona')),
                ('USU_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago_Comprobante',
            fields=[
                ('PCO_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CPA_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloPagos.comprobante_pago')),
                ('PAP_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloPagos.pago_persona')),
            ],
        ),
        migrations.CreateModel(
            name='Prepago',
            fields=[
                ('PPA_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PPA_VALOR', models.DecimalField(decimal_places=6, max_digits=21)),
                ('PPA_OBSERVACION', models.CharField(max_length=500, null=True)),
                ('PPA_VIGENTE', models.BooleanField(default=True)),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.curso')),
                ('PAP_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ModuloPagos.pago_persona')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona')),
            ],
        ),
    ]
