# Generated by Django 5.2.6 on 2025-10-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto_Contable',
            fields=[
                ('COC_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('COC_DESCRIPCION', models.CharField(max_length=100)),
                ('COC_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('PRV_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('PRV_DESCRIPCION', models.CharField(max_length=100)),
                ('PRV_CELULAR1', models.CharField(blank=True, max_length=15, null=True)),
                ('PRV_CELULAR2', models.CharField(blank=True, max_length=15, null=True)),
                ('PRV_DIRECCION', models.CharField(blank=True, max_length=100, null=True)),
                ('PRV_OBSERVACION', models.CharField(blank=True, null=True)),
                ('PRV_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
    ]
