# Generated by Django 5.2.6 on 2025-10-18 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloCursos', '0002_alter_curso_alimentacion_ali_id_and_more'),
        ('ModuloPagos', '0001_initial'),
        ('ModuloUsuarios', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto_contable',
            name='COC_DESCRIPCION',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='concepto_contable',
            name='COC_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='PRV_CELULAR1',
            field=models.CharField(blank=True, default=999999999, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='PRV_DIRECCION',
            field=models.CharField(blank=True, default='s', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='PRV_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Comprobante_Pago',
            fields=[
                ('CPA_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CPA_FECHA_HORA', models.DateTimeField()),
                ('CPA_FECHA', models.DateField(auto_now_add=True)),
                ('CPA_NUMERO', models.IntegerField()),
                ('CPA_VALOR', models.DecimalField(decimal_places=2, max_digits=21)),
                ('COC_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloPagos.concepto_contable')),
                ('PEC_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarios.persona_curso')),
                ('USU_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago_Persona',
            fields=[
                ('PAP_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PAP_FECHA_HORA', models.DateTimeField()),
                ('PAP_VALOR', models.DecimalField(decimal_places=6, max_digits=21)),
                ('PAP_OBSERVACION', models.CharField(max_length=500, null=True)),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloCursos.curso')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarios.persona')),
                ('USU_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago_Comprobante',
            fields=[
                ('PCO_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CPA_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloPagos.comprobante_pago')),
                ('PAP_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloPagos.pago_persona')),
            ],
        ),
        migrations.CreateModel(
            name='Prepago',
            fields=[
                ('PPA_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PPA_VALOR', models.DecimalField(decimal_places=6, max_digits=21)),
                ('PPA_OBSERVACION', models.CharField(max_length=500, null=True)),
                ('PPA_VIGENTE', models.BooleanField(default=True)),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloCursos.curso')),
                ('PAP_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ModuloPagos.pago_persona')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarios.persona')),
            ],
        ),
    ]
