# Generated by Django 5.2.6 on 2025-10-15 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ModuloUsuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo_Persona',
            fields=[
                ('ARP_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Archivo',
            fields=[
                ('TAR_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TAR_DESCRIPCION', models.CharField(max_length=50)),
                ('TAR_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('ARC_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ARC_FECHA_HORA', models.DateTimeField(auto_now_add=True)),
                ('ARC_DESCRIPCION', models.CharField(max_length=100)),
                ('ARC_RUTA', models.CharField()),
                ('ARC_VIGENTE', models.BooleanField(default=True)),
                ('USU_ID_CREA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_crea', to='ModuloUsuarios.usuario')),
                ('USU_ID_MODIFICA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_modifica', to='ModuloUsuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo_Curso',
            fields=[
                ('ARU_ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('ARC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloArchivos.archivo')),
            ],
        ),
    ]
