# Generated by Django 5.2.6 on 2025-10-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ModuloUsuarioCurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Archivo',
            fields=[
                ('TAR_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TAR_DESCRIPCION', models.CharField(max_length=50)),
                ('TAR_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('ARC_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ARC_FECHA_HORA', models.DateTimeField(auto_now_add=True)),
                ('ARC_DESCRIPCION', models.CharField(max_length=100)),
                ('ARC_RUTA', models.CharField(max_length=255)),
                ('ARC_VIGENTE', models.BooleanField(default=True)),
                ('USU_ID_CREA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_crea', to='ModuloUsuarioCurso.usuario')),
                ('USU_ID_MODIFICA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modifica', to='ModuloUsuarioCurso.usuario')),
                ('TAR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloArchivos.tipo_archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo_Curso',
            fields=[
                ('ARU_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ARC_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloArchivos.archivo')),
                ('CUS_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo_Persona',
            fields=[
                ('ARP_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ARC_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloArchivos.archivo')),
                ('CUS_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarioCurso.curso')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona')),
            ],
        ),
    ]
