# Generated by Django 5.2.6 on 2025-10-15 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ModuloArchivos', '0001_initial'),
        ('ModuloCursos', '0001_initial'),
        ('ModuloUsuarios', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo_curso',
            name='CUS_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloCursos.curso'),
        ),
        migrations.AddField(
            model_name='archivo_persona',
            name='ARC_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloArchivos.archivo'),
        ),
        migrations.AddField(
            model_name='archivo_persona',
            name='CUS_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloCursos.curso'),
        ),
        migrations.AddField(
            model_name='archivo_persona',
            name='PER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarios.persona'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='TAR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloArchivos.tipo_archivo'),
        ),
    ]
