# Generated by Django 5.2.6 on 2025-10-18 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuloArchivos', '0002_initial'),
        ('ModuloCursos', '0001_initial'),
        ('ModuloUsuarios', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='ARC_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='ARC_RUTA',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='TAR_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloArchivos.tipo_archivo'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='USU_ID_CREA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_crea', to='ModuloUsuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='USU_ID_MODIFICA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modifica', to='ModuloUsuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='archivo_curso',
            name='ARC_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloArchivos.archivo'),
        ),
        migrations.AlterField(
            model_name='archivo_curso',
            name='ARU_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archivo_curso',
            name='CUS_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloCursos.curso'),
        ),
        migrations.AlterField(
            model_name='archivo_persona',
            name='ARC_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloArchivos.archivo'),
        ),
        migrations.AlterField(
            model_name='archivo_persona',
            name='ARP_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archivo_persona',
            name='CUS_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ModuloCursos.curso'),
        ),
        migrations.AlterField(
            model_name='archivo_persona',
            name='PER_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarios.persona'),
        ),
    ]
