# Generated by Django 5.2.6 on 2025-10-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ModuloMantenedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('APL_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('APL_DESCRIPCION', models.CharField(max_length=50)),
                ('APL_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('PEL_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PEL_DESCRIPCION', models.CharField(max_length=50)),
                ('PEL_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Curso',
            fields=[
                ('TCU_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TCU_DESCRIPCION', models.CharField(max_length=100)),
                ('TCU_TIPO', models.IntegerField(choices=[(1, 'Inicial'), (2, 'Medio'), (3, 'Avanzado'), (4, 'Habilitación'), (5, 'Verificación'), (6, 'Institucional')])),
                ('TCU_CANT_PARTICIPANTE', models.IntegerField(null=True)),
                ('TCU_VIGENTE', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('CURS_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CUR_FECHA_HORA', models.DateTimeField(auto_now_add=True)),
                ('CUR_FECHA_SOLICITUD', models.DateField()),
                ('CUR_CODIGO', models.CharField(max_length=20, unique=True)),
                ('CUR_DESCRIPCION', models.CharField(max_length=255)),
                ('CUR_OBSERVACION', models.CharField(blank=True, max_length=255, null=True)),
                ('CUR_ADMINISTRA', models.IntegerField(choices=[(2, 'Zona'), (2, 'Distrito')])),
                ('CUR_COTA_CON_ALMUERZO', models.IntegerField()),
                ('CUR_COTA_SIN_ALMUERZO', models.IntegerField()),
                ('CUR_MODALIDAD', models.IntegerField(choices=[(1, 'Internado'), (2, 'Externado'), (3, 'Internado/Externado')])),
                ('CUR_TIPO_CURSO', models.IntegerField(choices=[(1, 'Presencial'), (2, 'Online'), (3, 'Hibrido')])),
                ('CUR_LUGAR', models.CharField(max_length=100)),
                ('CUR_ESTADO', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Vigente'), (2, 'Anulado'), (3, 'Finalizado')])),
                ('CAR_ID_RESPONSABLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_responsable', to='ModuloMantenedores.cargo')),
                ('COM_ID_LUGAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_lugar', to='ModuloMantenedores.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Alimentacion',
            fields=[
                ('CUA_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CUA_FECHA', models.DateField()),
                ('CUA_TIEMPO', models.IntegerField(choices=[(1, 'Desayuno'), (2, 'Almuerzo'), (3, 'Once'), (4, 'Cena'), (5, 'Once/Cena')])),
                ('CUA_DESCRIPCION', models.CharField(max_length=100)),
                ('CUA_CANTIDAD_ADICIONAL', models.IntegerField(default=0)),
                ('CUA_VIGENTE', models.BooleanField(default=True)),
                ('ALI_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.alimentacion')),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Cuota',
            fields=[
                ('CUU_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CUU_TIPO', models.IntegerField(choices=[(1, 'Con Almuerzo'), (2, 'Sin Almuerzo')])),
                ('CUU_FECHA', models.DateField()),
                ('CUU_VALOR', models.DecimalField(decimal_places=6, max_digits=21)),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Fecha',
            fields=[
                ('CUF_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CUF_FECHA_INICIO', models.DateField()),
                ('CUF_FECHA_TERMINO', models.DateField()),
                ('CUF_TIPO', models.IntegerField(choices=[(1, 'Presencial'), (2, 'Online'), (3, 'Hibrido')])),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Seccion',
            fields=[
                ('CUS_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CUS_SECCION', models.IntegerField()),
                ('CUS_CANT_PARTICIPANTE', models.IntegerField()),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.curso')),
                ('RAM_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_Aplicacion',
            fields=[
                ('PEA_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PEA_INGRESAR', models.BooleanField(default=False)),
                ('PEA_MODIFICAR', models.BooleanField(default=False)),
                ('PEA_ELIMINAR', models.BooleanField(default=False)),
                ('PEA_CONSULTAR', models.BooleanField(default=False)),
                ('APL_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.aplicacion')),
                ('PEL_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('PER_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PER_FECHA_HORA', models.DateTimeField(auto_now_add=True)),
                ('PER_RUN', models.CharField(max_length=9, unique=True)),
                ('PER_DV', models.CharField(max_length=1)),
                ('PER_APELPTA', models.CharField(max_length=50)),
                ('PER_APELMAT', models.CharField(max_length=50, null=True)),
                ('PER_NOMBRES', models.CharField(max_length=50)),
                ('PER_MAIL', models.CharField(max_length=100)),
                ('PER_FECHA_NAC', models.DateField()),
                ('PER_DIRECCION', models.CharField(max_length=255)),
                ('PER_TIPO_FONO', models.IntegerField(choices=[(1, 'Fono Fijo'), (2, 'Celular'), (3, 'Celular/WhatsApp'), (4, 'WhatsApp')])),
                ('PER_FONO', models.CharField(blank=True, max_length=15)),
                ('PER_ALERGIA_ENFERMEDAD', models.CharField(max_length=255, null=True)),
                ('PER_LIMITACION', models.CharField(max_length=255, null=True)),
                ('PER_NOM_EMERGENCIA', models.CharField(max_length=50, null=True)),
                ('PER_FONO_EMERGENCIA', models.CharField(max_length=15, null=True)),
                ('PER_OTROS', models.CharField(max_length=255, null=True)),
                ('PER_NUM_MMA', models.IntegerField(null=True)),
                ('PER_PROFESION', models.CharField(max_length=100, null=True)),
                ('PER_TIEMPO_NNAJ', models.CharField(max_length=100, null=True)),
                ('PER_TIEMPO_ADULTO', models.CharField(max_length=100, null=True)),
                ('PER_RELIGION', models.CharField(max_length=100, null=True)),
                ('PER_APODO', models.CharField(max_length=50)),
                ('PER_FOTO', models.CharField(max_length=255, null=True)),
                ('PER_VIGENTE', models.BooleanField(default=True)),
                ('COM_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.comuna')),
                ('ESC_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.estado_civil')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Formador',
            fields=[
                ('CUF_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CUO_DIRECTOR', models.BooleanField(default=False)),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.curso')),
                ('ROL_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.rol')),
                ('CUS_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.curso_seccion')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Curso_Coordinador',
            fields=[
                ('CUC_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CUC_CARGO', models.CharField(max_length=100, null=True)),
                ('CAR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.cargo')),
                ('CUR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.curso')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='PER_ID_RESPONSABLE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarioCurso.persona'),
        ),
        migrations.CreateModel(
            name='Persona_Curso',
            fields=[
                ('PEC_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PEC_OBSERVACION', models.CharField(blank=True, max_length=500, null=True)),
                ('PEC_REGISTRO', models.BooleanField(default=False)),
                ('PEC_ACREDITACION', models.BooleanField(default=False)),
                ('ALI_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.alimentacion')),
                ('CUS_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.curso_seccion')),
                ('NIV_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.nivel')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona')),
                ('ROL_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Formador',
            fields=[
                ('PEF_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PEF_HAB_1', models.BooleanField(default=False)),
                ('PEF_HAB_2', models.BooleanField(default=False)),
                ('PEF_VERIF', models.BooleanField(default=False)),
                ('PEF_HISTORIAL', models.CharField(blank=True, max_length=500, null=True)),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Grupo',
            fields=[
                ('PEG_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PEG_VIGENTE', models.BooleanField(default=True)),
                ('GRU_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.grupo')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Individual',
            fields=[
                ('PEI_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PEI_VIGENTE', models.BooleanField(default=True)),
                ('CAR_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.cargo')),
                ('DIS_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.distrito')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona')),
                ('ZON_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Nivel',
            fields=[
                ('PEN_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('NIV_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.nivel')),
                ('PER_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona')),
                ('RAM_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloMantenedores.rama')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Vehiculo',
            fields=[
                ('PEV_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PEV_MARCA', models.CharField(max_length=50)),
                ('PEV_MODELO', models.CharField(max_length=50)),
                ('PEV_PATENTE', models.CharField(max_length=10)),
                ('PEC_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona_curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='TCU_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarioCurso.tipo_curso'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('USU_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('USU_USERNAME', models.CharField(max_length=100, unique=True)),
                ('USU_PASSWORD', models.CharField(max_length=50)),
                ('USU_RUTA_FOTO', models.CharField(max_length=255)),
                ('USU_VIGENTE', models.BooleanField(default=True)),
                ('PEL_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Estado_Curso',
            fields=[
                ('PEU_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PEU_FECHA_HORA', models.DateTimeField(auto_now_add=True)),
                ('PEU_ESTADO', models.IntegerField(choices=[(1, 'Pre Inscrito'), (2, 'Avisado'), (3, 'Lista de Espera'), (4, 'Inscrito'), (5, 'Vigente'), (6, 'Anulado'), (7, 'Sobrecupo')])),
                ('PEU_VIGENTE', models.BooleanField(default=True)),
                ('PEC_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.persona_curso')),
                ('USU_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='USU_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModuloUsuarioCurso.usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='USU_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuloUsuarioCurso.usuario'),
        ),
    ]
